# Generated by Django 5.1.2 on 2024-11-01 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PriceOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('initial', models.IntegerField()),
                ('final', models.IntegerField()),
                ('discount_percent', models.IntegerField()),
                ('initial_formatted', models.CharField(blank=True, max_length=50)),
                ('final_formatted', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('steam_appid', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('header_image', models.URLField()),
                ('genres', models.ManyToManyField(to='wishlists.genre')),
                ('price_overview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wishlists.priceoverview')),
            ],
        ),
    ]
