# Generated by Django 5.1.2 on 2024-10-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('language', models.CharField(max_length=400)),
                ('price', models.CharField(max_length=20)),
            ],
        ),
    ]
