# Generated by Django 5.1.2 on 2024-11-20 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='price_overview',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='PriceOverview',
        ),
    ]
